ilios/iliosproject.org

- CNAME
Reverts ilios/ilios.github.io#3
mergie McMergerson on the rampage
> Revert "CNAME"

- MyReports.html
from http://saschaben.users.sonic.net/IliosSample/MyReports.html
> WIP: added my reports matrix.

- technology.md
Apache: 2.2.15
Mysql: 5.1
Php: 5.4.4
Fixes https://github.com/ilios/ilios/issues/1143
> Update technology requirements for Ilios 3

- myreports.html
modify image links to point to actual directory, and make filename lowercase
> modify image links to point to actual directory

- calendar_offline.html
point moodle here during maintenance window. remove afterwards.
> add "calendar is offline" page, temporarily. 

- _config.yml
- _includes/header.html
- _layouts/page.html
- _layouts/post.html
- css/main.scss
- index.md
added home button to nav; cleaned up news post header layouts; minor
header tag cleanups.
> home button

- _includes/header.html
- _posts/2016-01-07-happy.newyear.markdown
added news post; modified status report link to point to new mail chimp
online archive.
> 01.07.2016.update

- _posts/2016-06-13-3130release.markdown
- contact-us.md
- subscribe.md
> monthly updates

- _layouts/unrestricted-width.html
- _sass/_layout.scss
- features.md
- myreports.md
This PR adds an expanded reports grid to show potential new report models; it also creates a modified layout to allow for oversized content without a narsty left-margin gutter pushing the table out of the layout grid.
> Add MyReports table page

- index.md
> fixed link to user guide refs #63

- .editorconfig
- _layouts/default.html
- _layouts/post.html
- _layouts/unrestricted-width.html
and reformatted layout templates.
> Added editorconfig file

- _posts/2016-12-19-updates.markdown
- _posts/2017-01-13-updates.markdown
> New year updates

- _posts/2017-01-27-updates.markdown
updates for the today's release
> updates for 3.25.0 release

- _posts/2017-05-06-updates.markdown
> v332 release note

- _posts/2017-06-01-updates.markdown
> June1_update

- _posts/2017-07-18-updates.markdown
> add some tips

- team.md
add Geoff to the list, update Gaby to contributor
> team-update

- _posts/2017-10-13-updates.markdown
I was trying to fix the "it's" to be the correct "its" in several places.
Supersedes #99
> friday13updates

- _posts/2017-11-17-updates.markdown
> nov17update

- _includes/header.html
- _sass/_layout.scss
corrects spacing of nabber and adds ilios orange to home link
> fixed home link on navbar

- _includes/header.html
- _sass/_layout.scss
refines the layout, spacing, and consistency of the nav menu bar in large and small formats.
> Mobile modifier

- team.md
> listed former contributors in emeritus section

- _posts/2018-08-21-updates.markdown
- hosting-pricing.md
- hosting.md
- parking-pricing.md
adds 3.53.1 updates, pricing grid, and more hosting info.
> Pricing updates

- _posts/2018-18-21-updates.markdown
- index.md
3.55.0 update, plus link menu improvements.
> Yom kippur updates

- _posts/2018-09-29-updates.markdown
added meme pic to excite the masses.
> Pre-October update

- about.md
Just a suggestion. Take it or leave it...
> revise about.md lede

- _posts/2019-06-28-updates.markdown
- _posts/2019-08-08-updates.markdown
> August updates

- .gitignore
- about.md
also adds bullet to emphasize open sourceness.
> Add mission and vision statement to about page

- _includes/footer.html
- _sass/_base.scss
Moved the UCSF / Medbiquitous to it's own row.
This badge is required by Netlify's OSS policy and I don't mind throwing them a little bit of free advertising since they do a lot of great stuff for us.
> Add netlify badge to footer

- _sass/_base.scss
- _sass/_layout.scss
- index.md
- technology.md
- timeline.md
updates to tech reqs, timeline, index link menu, and a few other minor tweaks.
> 2020 updates 2

- _posts/2022-06-06-updates.markdown
> June22 updates

- team.md
> add Brandon to team list

- _includes/header.html
- _sass/_layout.scss
while at it, ensure that the homepage link is indicated as active and displayed on the homepage.
fixes #199
> indicate active page in nav bar.

- _sass/_base.scss
- _sass/_layout.scss
see https://sass-lang.com/documentation/breaking-changes/slash-div/
fixes #219
> fixes SCSS deprecations by wrapping slash-divisions in calls to calc().

- Gemfile
- Gemfile.lock
> explicitly add CSV gem as dependency.

- team.md
Added my name and Github username to the team members :D
> added my name to the team

- _includes/footer.html
- _includes/header.html
- _sass/_layout.scss
**Desktop**
* Improved Performance rating from 99 to **100** by adding height/width to some images
* Improved Accessibility from 84 to **93** by changing footer image structure from `<ul>` to `<div>`
**Mobile**
* Improved Accessibility from 86 to **96** by changing mobile menu icon from `<a class>` to `<button id>` and adding an `aria-label`
> improve Google Lighthouse performance and accessibility

- technology.md
Fixes #92 (and improves further)
> update technology section

- _includes/footer.html
> removed missing/unused remote script call

- Gemfile.lock
> Updated Bundler to latest version
